language: erlang

before_script:
  - kerl list installations

otp_release:
  - 18.1
  - 18.2
  - 18.3
  - 19.0
  - 19.1
  - 19.2

sudo: false
install: true
script:
  - ./rebar3 ct

branches:
  only:
  - master
  - dev
  - test
